### PR TITLE
compose with generator-travis insteadof using internal one

### PR DESCRIPTION
**Pull request by iamstarkov**
as we discussed in #13, created pr for composing with [generator-travis](https://github.com/iamstarkov/generator-travis)

### CODE REVIEW

**Comment by bucaran** [comment]
I like this! Thanks @iamstarkov

**Comment by iamstarkov** [comment]
Yay, thank you for appreciation 💫

**Comment by iamstarkov** [comment]
can you publish new version with these changes?

**Comment by bucaran** [comment]
v1.7.0 :up:

**Comment by bucaran** [comment]
@iamstarkov Any idea why the build broke?

**Comment by iamstarkov** [comment]
>   ✖ No tests found

Something is wrong with tests, I think

**Comment by iamstarkov** [comment]
Also you can install babel-cli as a devDeps and it will let you run babel-node in the npm scripts

**Comment by iamstarkov** [comment]
yep, its the case

**Comment by iamstarkov** [comment]
the problem with new Babeljs version

**Comment by iamstarkov** [comment]
wait a minute

**Comment by iamstarkov** [comment]
will fix it

**Comment by iamstarkov** [comment]
basically it wasnt my issue, but only problem was `"babel": "*"` in deps

**Comment by iamstarkov** [comment]
created pr #16

**Pull request merged**
