### PR TITLE
implement babel support into generated projects

### PR DESCRIPTION
**Pull request by iamstarkov**
finally babel fix for generated projects

### CODE REVIEW

**Comment by bucaran** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by iamstarkov** [comment]
i tested it locally and now generated projects are successfully able to be tested and covered

**Comment by bucaran** [comment]
:facepunch:

**Comment by bucaran** [comment]
BTW @iamstarkov I added you as a collaborator, so you create your own whatever-branches or push to master too. 

Thanks for all the work to make this work with Babel.

**Comment by iamstarkov** [comment]
@bucaran ありがとう

**Comment by bucaran** [comment]
@iamstarkov Dyakuyu!

**Comment by iamstarkov** [comment]
we need one small fix

**Pull request merged**
