### PR TITLE
Use travis' new container infrastructure

### PR DESCRIPTION
**Pull request by knownasilya**
See the blog post here http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

### CODE REVIEW

**Comment by iamstarkov** [comment]
it’s too old post

**Comment by iamstarkov** [comment]
Actually we reverted the same pull request some times ago

**Comment by iamstarkov** [comment]
checkout this conversation https://github.com/bucaran/generator-rise/commit/ba51aaece5e283a874e6cf3ba678d92d7817427d

**Comment by iamstarkov** [comment]
> You no longer have to add sudo:false in .travis.yml to new repos to get the faster container-based infrastructure

**Comment by knownasilya** [comment]
:+1: good to know.

**Comment by iamstarkov** [comment]
u r welcome

**Pull request closed without merging**
