### PR TITLE
should fix

### PR DESCRIPTION
**Pull request by iamstarkov**
should fix breaking change delivered with babel v6

### CODE REVIEW

**Comment by iamstarkov** [comment]
but npm scripts are not working this way due to bug https://github.com/babel/babel/issues/2703

**Comment by iamstarkov** [comment]
before patch for babel will land, use babel@5.x

**Comment by iamstarkov** [comment]
on the other hand require hook is working fine https://travis-ci.org/iamstarkov/trim-html-tag/jobs/89302182

**Comment by iamstarkov** [comment]
at least mocha is better to use with babel v6 😜

**Comment by Hypercubed** [comment]
We should be aware that Babel v6 changed it's handling of default exports.  Pre v6 a CJS user of a generator-rise module could require this module using `require('camelModuleName')`.  With this PR `require('camelModuleName').default` is needed.  Alternatively you can lock in v5.

**Comment by iamstarkov** [comment]
@bucaran yo, i fixed builds for ya!

**Comment by bucaran** [comment]
:facepunch:

**Pull request merged**
