### PR TITLE
Freeze dependencies

### LINKED ISSUE #23: Freeze dependencies in package.json
I feel bad using this package, as the `package.json` sometimes uses `*` for dependencies. This is bad, as it can cause issues [like the one with Babel 6 on fly](https://github.com/bucaran/fly/issues/115#issuecomment-159949214).

The best option is to mark dependency version with a `^`, therefore using latest non-breaking version. Plus, dependencies are tracked with david-dm, so this is easy to update when there is a newer breaking dependency version.

### PR DESCRIPTION
**Pull request by marvinroger**
Fix #23

### CODE REVIEW

**Comment by iamstarkov** [comment]
should work

**Comment by iamstarkov** [comment]
checked with david https://david-dm.org/bucaran/generator-rise

**Comment by iamstarkov** [comment]
Thank you

**Comment by bucaran** [comment]
Thanks. Using `"*"` was too naive on my part.

**Comment by marvinroger** [comment]
@bucaran my pleasure, but yeah semver is BREAKING.FEATURE.FIX rather than MAJOR.MINOR.PATCH. So with `^` you're bulletproof. :smiley:

**Comment by iamstarkov** [comment]
except is someone prefers [sentimental versioning](http://sentimentalversioning.org/)

**Pull request merged**
