### PR TITLE
Fix issue with watching multiple test files

### PR DESCRIPTION
**Pull request by TYRONEMICHAEL**

### CODE REVIEW

**Comment by bucaran** [comment]
Just for the record, please explain what is the difference with simply using `babel-node`?

**Comment by TYRONEMICHAEL** [comment]
`babel-node` behaves exactly as `node`. So you cannot, for eg, do `node test/*.js` as it will only execute the first file in the directory. So if you have files `test/test1.js` and `test/test2.js`, only `test/test1.js` will be executed. Whereas `babel-tape-runner` will execute both files. Hope that makes sense.  It is only a few lines of code:

```
require('babel-core/register')
var path = require('path')
var glob = require('glob')

process.argv.slice(2).forEach(function (arg) {
  glob(arg, function (er, files) {
    if (er) throw er

    files.forEach(function (file) {
      require(path.resolve(process.cwd(), file))
    })
  })
})
```

I left the coverage script, but it suffers from the same issue as it only does coverage on the first file. I am not sure how to fix this and think it is an issue with iSparta. So unless I dig into the codebase of iSparta, I wont be sure.

**Comment by bucaran** [comment]
@TYRONEMICHAEL Gotcha. I see now.

So, even if we were able to process all the files in the command line, Sparta would still fail? I think we should focus on the Spartan issue, as having babel run multiple test files is a trivial fix.

**Comment by TYRONEMICHAEL** [comment]
I am all ears. Let me know what you come up with? I am curious to see if there is a better way to solve the issue instead of using babel-tape-runner. Maybe then we might find a simple issue to solving the coverage issue as well.

**Comment by bucaran** [comment]
@TYRONEMICHAEL I will create an issue over at the Spartan headquarters. In the mean time, what do you think of using your script inline?

```js
node -e 'require("babel/register"); process.argv.slice(1).forEach(function (f) {require(require("path").resolve(__dirname,f))})' test/*.js
```

**Comment by TYRONEMICHAEL** [comment]
Much prefer that. Opened up the issue a few days back [#72](https://github.com/douglasduteil/isparta/issues/72). Will try experiment with their codebase tonight.

**Comment by bucaran** [comment]
Thanks, great. Feel free to use the second script and send another PR if you are so inclined.

**Comment by TYRONEMICHAEL** [comment]
Came up with an elegant solution for the coverage issue I think. Will share it with you later.

**Comment by bucaran** [comment]
Awesome!

**Comment by TYRONEMICHAEL** [comment]
So I came up with a solution I quite like. `babel-node test/index.js | tap-spec`. Then in your `index.js` file, you import your tests. So an index eg would look like the following.

```
// Add tests to this file.
// Comment out tests you do not want to be tested
// import example from './test-i-dont-want-to/test.spec';

import actions from './actions/counter.spec';
import reducers from './reducers/counter.spec';
import components from './components/Counter.spec';
```

What I like about this pattern, it enables you to quickly turn on and turn off tests. This works with isparta as well. So the problem was not with iSparta, but rather with the way node and node-babel behave. Coverage eg: `babel-node node_modules/.bin/isparta cover --report text --report html test/index.js`

**Comment by bucaran** [comment]
:+1: 
I see. Thanks for making all this more clear @TYRONEMICHAEL 

Freel free to close at your discretion :smile:

**Pull request closed without merging**
